### ISSUE TITLE
[Survival Table] Buttons do nothing

### ISSUE THREAD

**Issue by gensakudan** [MaribelHearn/maribelhearn.com#18] opened 2022-06-23 07:43 UTC
**Describe the bug**
None of the buttons on the Survival Progress Table Generator page seem to do anything.

**To Reproduce**
1. Go to https://maribelhearn.com/survival
2. Click on any button
3. Observe how nothing happens

**Expected behavior**
- The `Fill All` button should fill in the table according to the settings of the drop-down lists above it.
- The `Save` button should save the table.
- The `Generate Tables` button should open up a modal with the generated survival table.
- The `Reset` button should reset the table.

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - Browser: Mozilla Firefox (64-bit)
 - Version 101.0.1

**Comment by MaribelHearn** [comment] 2022-06-23 08:53
This issue was caused by the erroneous presence of a value for IN FinalB Extra in local storage, despite Extra being stored under FinalA only.

Fixed as of [https://github.com/MaribelHearn/maribelhearn.com/commit/336a6bd3109fae3ff022c1c2f0c9e07fa2ed0aa8](url)

**Closed by MaribelHearn** 2022-06-23 08:53 UTC
